spring:
  application:
    name: ticket-app
  datasource:
    url: jdbc:postgresql://localhost:5432/ticket_app
    username: user
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0